export default {
    api: {
        micronutrient_dtl_json:{},
        fertilizer_dtl_json:{},
        optimized_output:{}
      },
    selects:{
      crop_name:'',
      irrigation_type_code:'',
      area_hectare:0,
      NPK_per_hectare:{
        N_per_hectare:0,
        P_per_hectare:0,
        K_per_hectare:0
      },
      NPK_total:{
        N_total:0,
        P_total:0,
        K_total:0
      },
      NPK_deficit:{
        N_deficit:0,
        P_deficit:0,
        K_deficit:0
      },
      NPK_soil_test_result:{
        N_soil_test_result:0,
        P_soil_test_result:0,
        K_soil_test_result:0
        }
      }
    }
